# Generated by Django 2.1.3 on 2018-11-15 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medal', models.CharField(max_length=250)),
                ('ServiecTime', models.CharField(max_length=250)),
                ('ResponseTime', models.CharField(max_length=250)),
                ('Date', models.CharField(max_length=250)),
                ('MostRecent', models.CharField(max_length=250)),
                ('ParentOrder', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.User'),
        ),
    ]
