# Generated by Django 2.1.3 on 2018-11-15 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20181115_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgreementInText', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='OrderName',
            field=models.CharField(default='defaultordername', max_length=250),
        ),
        migrations.AddField(
            model_name='agreements',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Order'),
        ),
    ]
