# Generated by Django 2.1.3 on 2018-11-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20181115_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ServiecTime',
            new_name='ServiceTime',
        ),
    ]
