# Generated by Django 2.1.3 on 2018-11-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20181115_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreements',
            name='Order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='User',
        ),
        migrations.DeleteModel(
            name='Agreements',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
