# Generated by Django 2.1.3 on 2018-11-28 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgreementInText', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderName', models.CharField(default='defaultordername', max_length=250)),
                ('Medal', models.CharField(max_length=250)),
                ('ServiceTime', models.CharField(max_length=250)),
                ('ResponseTime', models.CharField(max_length=250)),
                ('Date', models.CharField(max_length=250)),
                ('MostRecent', models.CharField(max_length=250)),
                ('ParentOrder', models.CharField(max_length=250)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agreements',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Order'),
        ),
    ]
