# Generated by Django 2.1.3 on 2018-11-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='User',
        ),
    ]
