# Generated by Django 2.1.3 on 2018-11-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='whatever',
            field=models.CharField(default='whatev', max_length=250),
        ),
    ]
