# Generated by Django 2.1.3 on 2018-11-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20181128_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ParentOrder',
            field=models.CharField(default='ORIGINAL', max_length=250),
        ),
    ]
