# Generated by Django 2.1.3 on 2018-11-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20181129_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='SystemId',
            field=models.CharField(default='UNDEFINED', max_length=250),
        ),
    ]
