# Generated by Django 2.1.3 on 2018-11-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_order_systemid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Object', models.CharField(max_length=50)),
                ('OS', models.CharField(max_length=50)),
                ('Packet', models.CharField(max_length=50)),
                ('SystemId', models.CharField(max_length=50)),
            ],
        ),
    ]
