# Generated by Django 2.1.3 on 2018-12-12 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_newresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newresource',
            name='system',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.SystemIdentif', to_field='SystemID'),
        ),
        migrations.AlterField(
            model_name='systemidentif',
            name='SystemID',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
