# Generated by Django 2.1.3 on 2018-12-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20181212_1304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resources',
        ),
    ]
