# Generated by Django 2.1.3 on 2018-12-13 10:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_delete_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckBoxType', models.CharField(max_length=250)),
                ('Info', models.BooleanField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='newresource',
            name='ResourceID',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.CharField(default=datetime.datetime(2018, 12, 13, 10, 11, 14, 406754, tzinfo=utc), max_length=250),
        ),
        migrations.AddField(
            model_name='completeorder',
            name='OrderName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.Order'),
        ),
        migrations.AddField(
            model_name='completeorder',
            name='ResourceID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.NewResource', to_field='ResourceID'),
        ),
        migrations.AddField(
            model_name='completeorder',
            name='SystemID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.SystemIdentif', to_field='SystemID'),
        ),
    ]
