# Generated by Django 2.1.3 on 2018-12-13 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_auto_20181213_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.CharField(default=datetime.datetime(2018, 12, 13, 13, 13, 44, 87705, tzinfo=utc), max_length=250),
        ),
    ]
