# Generated by Django 2.1.3 on 2018-12-14 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_auto_20181213_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.CharField(default=datetime.datetime(2018, 12, 14, 8, 31, 48, 369787, tzinfo=utc), max_length=250),
        ),
    ]
