# Generated by Django 2.1.3 on 2018-12-14 09:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_auto_20181213_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeorder',
            name='OrderName',
        ),
        migrations.RemoveField(
            model_name='completeorder',
            name='ResourceID',
        ),
        migrations.RemoveField(
            model_name='completeorder',
            name='SystemID',
        ),
        migrations.RenameField(
            model_name='agreements',
            old_name='AgreementInText',
            new_name='CheckBoxType',
        ),
        migrations.RemoveField(
            model_name='agreements',
            name='Order',
        ),
        migrations.AddField(
            model_name='agreements',
            name='OrderName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.Order'),
        ),
        migrations.AddField(
            model_name='agreements',
            name='ResourceID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.NewResource', to_field='ResourceID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.CharField(default=datetime.datetime(2018, 12, 14, 9, 30, 16, 100046, tzinfo=utc), max_length=250),
        ),
        migrations.DeleteModel(
            name='CompleteOrder',
        ),
    ]
