# Generated by Django 2.1.3 on 2018-12-14 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_auto_20181214_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.CharField(default=datetime.datetime(2018, 12, 14, 11, 51, 14, 338627, tzinfo=utc), max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderName',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
