# Generated by Django 2.1.3 on 2018-12-14 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_auto_20181214_0939'),
        ('API', '0019_auto_20181214_1258'),
    ]

    operations = [
    ]
