# Generated by Django 2.1.3 on 2018-12-20 07:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_merge_20181214_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='MostRecent',
            new_name='Status',
        ),
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.CharField(default=datetime.datetime(2018, 12, 20, 7, 57, 4, 716981, tzinfo=utc), max_length=250),
        ),
    ]
