# Generated by Django 2.1.3 on 2018-12-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_auto_20181220_0838'),
        ('API', '0021_auto_20181220_0757'),
    ]

    operations = [
    ]
