# Generated by Django 2.1.3 on 2018-12-20 11:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_merge_20181220_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreements',
            name='OrderName',
        ),
        migrations.AddField(
            model_name='agreements',
            name='orderID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.CharField(default=datetime.datetime(2018, 12, 20, 11, 39, 25, 688139, tzinfo=utc), max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderName',
            field=models.CharField(max_length=250),
        ),
    ]
